# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 189be6a42db0f53e6f2a794d892ddecba3f4ca446b804560a70fb596ebc8979cf126478c5c2dee1aaf530371dd5ebc4dfaf129585498195a5e2ed69740cb6b31

test:
  secret_key_base: 687dca90086c846dd448efd867beb74203ead21a0d98c61a7e14612489a80027b1ff2ef0a85e36a29f2876b1296b467f42ba3a0f5825586e032133a651e74e36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
